### PR TITLE
Value injection

### PR DESCRIPTION
**Pull request by dvidben**
Adds value injection support, precedence and attribute setting decorator.

### CODE REVIEW

**Comment by Dobiasd** [comment]
(As already discussed,) I think your contribution is really amazing! :rocket:

I've read and understood the (very well written!) documentation and the (good!) tests cases already. I'll dive into the implementation details tomorrow. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
For the CI to pass, could you try the following?
- Add a `pip install -r requirements.txt` to `ci.yml`.
- Add docstrings where required. (Yeah, I know the linter settings are unusually strict on that project.)
- Add a `# pylint: disable=` for `too-few-public-methods` and `too-many-arguments`. And for `too-many-locals` too, or refactor this function a bit. (Whatever you think makes more sense. :+1:)

**Comment by dvidben** [comment]
Awesome! Thank you for reviewing this.
I'll go over the CI required changes and let you know.

**Comment by dvidben** [comment]
Fixed the complaints and CI checks are all green on my end. I hope you see the same.

**Comment by Dobiasd** [comment]
Changes look good, and CI is happy now. :+1:

I've also now looked into the implementation details, and have some questions:
- `ENTERPRYTHON_VALUES` (and `def add_values`/`def set_values`/`def value`) are from the old (superseded) value store, and can be completely removed, right?
- Is there a reason to declare `stored_value: ValueType` in `def _enforce_type` outside of the try block?
- The `#dbenavid ...` things were just markers for you while developing, and should be removed, right?

Ah, and when we're ready to merge your work, would you like me to squash the commits into one, or keep the commit history as is? For me, both versions are ok, it's more about how you'd prefer your contribution to be reflected in the commit history in `master`. :slightly_smiling_face:

**Comment by dvidben** [comment]
Great to hear that!

- Sure, ENTERPRYTHON_VALUES are removed now. I was not sure you wanted me to make this change at this point.
- I'm removing the variable definition from the outside block. Good catch.
- It looks like there were still couple of markers there. I already removed them

On the merge question, keeping the original commits is fine with me. This shows the progress and your valuable feedback during the PR review.

**Comment by Dobiasd** [comment]
Great! So from my point of view, it looks perfect now, and I'm ready to merge. :tada:

Do you agree?

**Comment by dvidben** [comment]
Great, go ahead!

**Comment by Dobiasd** [comment]
Thanks again for this very cool contribution! :star_struck:

**Pull request merged**
